pool:
    vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: self
    - repository: templates
      type: git
      name: DevOps/common-pipeline-template-eks
      ref: refs/heads/feature/front_nodejs20

extends:
  template: templates/frontTemplate.yml@templates